sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:filename/

    projects:
        type: path
        permalink: projects/:filename/
        singular_name: project
        taxonomies:
            - tools
            - categories

    # # photography:
    #     type: path
    #     permalink: photography/:filename/
    #     singular_name: album
    #     taxonomies:
    #         - tools
    #         - categories
