site:
    name: Site Title Here
    legalName: Company Name
    owner:  Brandtley McMinn
    url: http://test.name
    timezone: America/Chicago

paging:
    postCount: 10
    pages: 5
    next: Next
    prev: Previous

address:
    street1:    4500 Testing
    street2:
    city:       Austin
    stateFull:  Texas
    state:      TX
    zipcode:    78759


navlists:
    header:
        -
            name: Blog
            route: /blog
    footer:
        -
            name: Sitemap
            route: /sitemap.xml


authors:
    brandtley:
        name: Brandtley McMinn
        # slug: brandtley-mcminn
        website: http://brandtley.name/
        social:
            -
                name: Facebook
                url:    https://facebook.com/blarg
            -
                name: Twitter
                url:    https://twitter.com/blarg
    bob:
        name: Bob Dole
        # slug: bob-dole
        website: http://bobdo.le/
        social:
            -
                name: Facebook
                url: https://facebook.com/boblarg
            -
                name: Instagram
                url: https://instagram.com/boblarg


defaultStyles:
    - /css/main.css
