site:
    name: Site Title Here
    legalName: Company Name
    owner:  Brandtley McMinn
    url: http://test.name
    timezone: America/Chicago


address:
    street1:    4500 Testing
    street2:
    city:       Austin
    stateFull:  Texas
    state:      TX
    zipcode:    78759

authors:
    brandtley:
        name: Brandtley McMinn
        website: http://brandtley.name/
        social:
            -
                name: Facebook
                url:    https://facebook.com/blarg
            -
                name: Twitter
                url:    https://twitter.com/blarg
    bob:
        name: Bob Dole
        website: http://bobdo.le/
        social:
            -
                name: Facebook
                url: https://facebook.com/boblarg
            -
                name: Instagram
                url: https://instagram.com/boblarg


defaultStyles:
    - /public/css/main.css
